config/routes.rb
Rails.application.routes.draw do

  resources :artists, :path => "Authors"

  resources :items

  resources :itemimages

  resources :carts

#  resources :userinfos

  resources :comments

  resources :likes

  resources :orders

  resources :carousels

  resources :pricerequests

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

	root "pages#home"
	get "paintings" => "pages#paintings"
	get "jewellery" => "pages#enamels", as: "enamels"
  get "textiles" => "pages#textiles"
  get "sculptures" => "pages#sculptures"
  get "channel" => "pages#channel"
  get "favorites" => "likes#index"
  get "AboutUs" => "pages#aboutus", as: "aboutus"
  get "Contact" => "pages#contact", as: "contact"
  get "MyFavorites" => "pages#favorites", as: "myfavorites"
  get "ordermanagement" => "pages#ordermanagement"
  get "requestmanagement" => "pages#requestmanagement"
  get 'sitemap.xml' => 'pages#sitemap', :defaults => { :format => 'xml' }

end

app/models/artist.rb
class Artist < ActiveRecord::Base
	has_many :items
	
	has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "200x200>" }

	validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
	validates :description, presence: true

	def to_param
		"#{id}-artist:#{name.gsub(/ /,"-")}"
	end

end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  before_action :set_artist, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :admin_user, except: [:index, :show]

  require 'will_paginate/array'

  respond_to :html

  def index
    @q = Artist.search(params[:q])
    @alphabet = ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z']
    if params[:start].present?
      artists = Artist.all.select{ |a| a.name.start_with?(params[:start].capitalize)}.sort_by!{ |m| m.name.downcase }
      if artists.length > 0
        @artists = artists.paginate(:page => params[:page], :per_page => 20)
      end 
    elsif params[:q].present?
      artists = @q.result
      if artists.length > 0
        @artists = artists.paginate(:page => params[:page], :per_page => 20)
      end 
    elsif params[:spec].present?
      @artists = Artist.where(:specialization => params[:spec]).paginate(:page => params[:page], :per_page => 20)
    else
      artists = Artist.reorder('name ASC')
      if artists.length > 0
        @artists = artists.paginate(:page => params[:page], :per_page => 20)
      end 
    end
    respond_with(@artists)
  end

  def show
    respond_with(@artist, @items = @artist.items)
  end

  def new
    @artist = Artist.new
    respond_with(@artist)
  end

  def edit
  end

  def create
    @artist = Artist.new(artist_params)
    @artist.save
    respond_with(@artist)
  end

  def update
    @artist.update(artist_params)
    respond_with(@artist)
  end

  def destroy
    @artist.destroy
    respond_with(@artist)
  end

  private
    def set_artist
      @artist = Artist.find(params[:id])
      @og_title = @artist.name.split.map(&:capitalize)*' '+' Artiveria Profile'
      @og_description = @artist.description
      @og_image = @artist.image.url(:medium)
    end

    def admin_user
      unless current_user.try(:admin?)
        redirect_to :root, notice: "Only admins are authorized for this"
      end
    end

    def artist_params
      params.require(:artist).permit(:name, :description, :rmore, :image, :specialization, :country, :manager, :phone_number, :secondary_phone_number, :email, :secondary_email )
    end
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/views/artists/_form.html.erb
<%= form_for @artist, html: { multipart: true } do |f| %>
  <% if @artist.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@artist.errors.count, "error") %> prohibited this artist from being saved:</h2>

      <ul>
      <% @artist.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %><br>
    <%= f.text_field :name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :description %><br>
    <%= f.text_area :description, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :rmore %><br>
    <%= f.text_area :rmore, class: "form-control" %>    
  </div>

  <div class="form-group">
    <%= f.label :specialization %><br>
    <%= f.select :specialization, [ 'Painter', 'Sculptor', 'Textile', 'Enamel'], class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :country %><br>
    <%= f.select :country, [ 'Georgia', 'Armenia', 'Azerbaijan', 'Turkey', 'Russia', 'Ukraine', 'USA' ], class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :manager %><br>
    <%= f.text_field :manager, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :phone_number %><br>
    <%= f.text_field :phone_number, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :secondary_phone_number %><br>
    <%= f.text_field :secondary_phone_number, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :email %><br>
    <%= f.text_field :email, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :secondary_email %><br>
    <%= f.text_field :secondary_email, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :image %>
    <%= f.file_field :image, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/artists/edit.html.erb
<h1>Editing artist</h1>

<%= render 'form' %>

<%= link_to 'Show', @artist %> |
<%= link_to 'Back', artists_path %>

app/views/artists/index.html.erb
<% if current_user.try(:admin?) %>
  <%= link_to 'New Artist', new_artist_path, style: "font-weight:bold;" %>
  <div style='width:100%; border-top:solid; margin-bottom:10px; margin-top:10px;'></div>
<% end %>

<div id='fixed-top' class='row' style='margin-bottom:0; padding-top:15px; background:white;'>
  <div class='col-md-8'>
    <p style="display:inline-block; font-weight:bold; font-size:110%; margin-right:10px; margin-bottom:20px;">Browse:</p>
    <% @alphabet.each do |character| %>
      <%= link_to character, artists_path(:start => character), style: 'font-weight:bold; margin-right:5px;' %>
    <% end %> | <%= link_to 'Clear', artists_path, style: 'font-weight:bold; margin-right:5px; color:#484848;' %>
    <div class="dropdown" style='display:inline-block; margin-left:10px;'>
      <button class='btn btn-default' id="dLabel" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        Specialization
        <span class="caret"></span>
      </button>
      <ul class="dropdown-menu" role="menu" aria-labelledby="dLabel">
        <li style='text-align:center;'><%= link_to 'Painter', artists_path(spec: 'Painter'), style: 'color:#337ab7; font-weight:bold;' %></li>
        <li class='divider'></li>
        <li style='text-align:center;'><%= link_to 'Jewellery', artists_path(spec: 'Enamel'), style: 'color:#337ab7; font-weight:bold;' %></li>
        <li class='divider'></li>
        <li style='text-align:center;'><%= link_to 'Textile', artists_path(spec: 'Textile'), style: 'color:#337ab7; font-weight:bold;' %></li>
        <li class='divider'></li>
        <li style='text-align:center;'><%= link_to 'Sculptor', artists_path(spec: 'Sculptor'), style: 'color:#337ab7; font-weight:bold;' %></li>
      </ul>
    </div>
  </div>
  <div class='col-md-4'>
    <div style='width:100%; margin-top:-5px; margin-bottom:10px;'>
      <%= search_form_for @q, html: { class: 'input-group', style: 'width:200px; margin-left:auto; margin-right:auto;'} do |f| %>
        <span class="input-group-btn">
          <button type='submit;' class="btn btn-default" type="button" style='-webkit-border-top-right-radius: 0px;-webkit-border-bottom-right-radius: 0px;-moz-border-radius-topright: 0px;-moz-border-radius-bottomright: 0px;border-top-right-radius: 0px;border-bottom-right-radius: 0px; border-right:none;'><i class="fa fa-search fa-lg"></i></button>
        </span><%= f.search_field :name_cont, placeholder: 'Search...', class: 'form-control', style: 'margin-left:-1px;' %>
      <% end %>
    </div>
  </div>
</div>

<div id='loading' style='margin-left:auto; margin-right:auto; margin-top:20px; width:180px; height:130px; background-image:url("../assets/loading.gif"); background-repeat: no-repeat; background-position:-200px -150px;'>
</div>

<% if @artists.present? %>
  <div id='after-load' style='display:none;'>
    <div id="container" style='margin-left:auto; margin-right:auto;'>
      <% @artists.each do |artist| %>
        <div class='artist' style='text-align:center; margin-right:15px; margin-left:15px; margin-bottom:50px; width:200px;'>
          <%= link_to image_tag(artist.image.url(:thumb)), artist %>
          <div class="panel-body">
              <%= link_to artist, style: 'text-decoration:none; color: #484848;' do %><p class='artist-name'><%= artist.name %></p><% end %>
            <div class="actions">
              <% if current_user.try(:admin?) %>
              <%= link_to 'Edit', edit_artist_path(artist) %>
              <%= link_to 'Destroy', artist, method: :delete, data: { confirm: 'Are you sure?' } %>
              <% end %>
            </div>
          </div>
        </div>
      <% end %>
    </div>

    <div style='text-align:center;'>
       <%= will_paginate @artists, renderer: BootstrapPagination::Rails %>
    </div>
  </div>
<% else %>
  <script>
    var n = noty({
      text: '<p style="width:100%; margin-top:15px; margin-bottom:15px; text-align:center; font-weight:bold; font-size:120%;">We do not have such artist.</p>',
      layout: 'topRight',
      type: 'information',
      animation: {
        open: 'animated fadeInRight', // Animate.css class names
        close: 'animated flipOutY', // Animate.css class names
        speed: 500 // unavailable - no need
      }
    });
    </script>
<% end %>

<script>
var isotopeLaunch = function(){
  var $container = $('#container');
    // init

    $container.isotope({
      // options
      itemSelector: '.artist',
      layoutMode: 'fitRows',
    });
};
imagesLoaded( 'img', function(){
  $('#loading').hide();
  $('#after-load').show();
  isotopeLaunch();
});

 fixed_auth = $('#fixed-top');
 offset_auth = $('#fixed-top').offset();
  $(window).scroll(function(e){
    width = $('#fixed-top').width();
    if ($(this).scrollTop() > offset_auth.top && fixed_auth.css('position') != 'fixed'){
      fixed_auth.css({'position': 'fixed', 'top': '0px', 'z-index': '1', 'width': width+'px'});
    }else if ($(this).scrollTop() < offset_auth.top && fixed_auth.css('position') == 'fixed' ){
      fixed_auth.css({'position': 'relative', 'border-bottom': 'none', 'z-index': '0'});
    }
  });
</script>

app/views/artists/new.html.erb
<h1>New artist</h1>

<%= render 'form' %>

<%= link_to 'Back', artists_path %>

app/views/artists/show.html.erb
<% if current_user.try(:admin?) %>
	<%= link_to 'Edit', edit_artist_path(@artist) %> |
	<%= link_to 'Back', artists_path %>
	<div style='width:100%; border-top:solid; margin-top:20px;'></div>
<% end %>

<div class='container' style='margin-top:30px;'>
	<div class='row'>
		<div class="col-md-4" style='text-align:center;'>
			<div class='author-image' oncontextmenu="return false" style='margin-bottom:20px;'>
				<%= image_tag @artist.image.url(:medium) %>
			</div>
		</div>
		<div class="col-md-8">
			<p style='font-weight:bold; font-size:200%;'><%= @artist.name %></p>
			<%= @artist.description.gsub(/\n/, '<br/>').html_safe %>
      <% if @artist.rmore.present? %>
        <a href='#' data-toggle='modal' data-target='#readmore'>Read more...</a>
      <% end %>
		</div>
	</div>
</div>

<div style='width:100%; border-top:solid; border-width:2px; margin-bottom:10px; margin-top:20px;'></div>

<p style='margin-bottom:20px; font-size:150%; font-weight:bold;'>
	More From <%= @artist.name %>:
</p>

<div id="container" style='display:none;'>
  <% @items.each do |item| %>
    <div class='item' style='text-align:center; margin-right:20px; margin-left:20px; width:340px; margin-bottom:50px;'>
      <%= link_to item do %>
        <%= image_tag item.image.url(:medium), style: "margin-right:auto; margin-left:auto;-webkit-box-shadow: 7px 7px 5px 0px rgba(50, 50, 50, 0.75);-moz-box-shadow:    7px 7px 5px 0px rgba(50, 50, 50, 0.75);box-shadow:         7px 7px 5px 0px rgba(50, 50, 50, 0.75); margin-bottom:15px;" %>
      <% end %>
      <%= link_to item.name.split.map(&:capitalize)*' ', item, style: "text-decoration:none; color:#444; margin-left:auto; margin-right:auto; font-weight:bold; display:block; margin-bottom:0px;" %>
      <%= link_to item.artist.name.split.map(&:capitalize)*' ', item.artist, style: "text-decoration:none; color:#444; margin-left:auto; margin-right:auto; margin-top:0px; display:block;" %>
      <% if item.price.present? %><div class='price'><%= '$ '+item.price.to_s %></div><% end %>
    </div>
  <% end %>
</div>

<div class="modal fade" id="readmore" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog" style="margin-top:100px;">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="myModalLabel" style="font-weight:700;"><%= @artist.name %></h4>
      </div>
      <div class="modal-body">
        <% if @artist.rmore.present? %>
          <%= @artist.rmore.gsub(/\n/, '<br/>').html_safe %>
        <% end %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

<script>
var isotopeLaunch = function(){
  var $container = $('#container');
  $container.show();
    // init
    $container.isotope({
      // options
      itemSelector: '.item',
      layoutMode: 'fitRows',
    });
};
imagesLoaded( 'img', isotopeLaunch);
</script>