config/routes.rb
Rails.application.routes.draw do

  resources :artists, :path => "Authors"

  resources :items

  resources :itemimages

  resources :carts

#  resources :userinfos

  resources :comments

  resources :likes

  resources :orders

  resources :carousels

  resources :pricerequests

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

	root "pages#home"
	get "paintings" => "pages#paintings"
	get "jewellery" => "pages#enamels", as: "enamels"
  get "textiles" => "pages#textiles"
  get "sculptures" => "pages#sculptures"
  get "channel" => "pages#channel"
  get "favorites" => "likes#index"
  get "AboutUs" => "pages#aboutus", as: "aboutus"
  get "Contact" => "pages#contact", as: "contact"
  get "MyFavorites" => "pages#favorites", as: "myfavorites"
  get "ordermanagement" => "pages#ordermanagement"
  get "requestmanagement" => "pages#requestmanagement"
  get 'sitemap.xml' => 'pages#sitemap', :defaults => { :format => 'xml' }

end

app/models/carousel.rb
class Carousel < ActiveRecord::Base

	belongs_to :item

	has_attached_file :image, :styles => {:medium => "x500"}

	validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
	validates :headline, presence: true
	validates :description, presence: true

end

app/controllers/carousels_controller.rb
class CarouselsController < ApplicationController
  before_action :set_carousel, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:show]
  before_action :admin_user, except: [:show]

  respond_to :html

  def index
      @carousels = Carousel.all
      respond_with(@carousels)
  end

  def show
    respond_with(@carousel)
  end

  def new
    unless params[:artist_id].present?
      @items = Item.all
    else
      @items = Item.where(:artist_id => params[:artist_id])
    end
    @carousel = Carousel.new
    respond_with(@carousel)
  end

  def edit
    unless params[:artist_id].present?
      @items = Item.all
    else
      @items = Item.where(:artist_id => params[:artist_id])
    end
  end

  def create
    @carousel = Carousel.new(carousel_params)
    @carousel.save
    respond_with(@carousel)
  end

  def update
    @carousel.update(carousel_params)
    respond_with(@carousel)
  end

  def destroy
    @carousel.destroy
    redirect_to carousels_path
  end

  private
    def set_carousel
      @carousel = Carousel.find(params[:id])
    end

    def admin_user
      unless current_user.try(:admin?)
        redirect_to :root, notice: "Only admins are authorized for this"
      end
    end

    def carousel_params
      params.require(:carousel).permit(:headline, :description, :image, :item_id, :textcolor, :placerank)
    end
end

app/views/carousels/_form.html.erb
<%= form_for @carousel, html: { multipart: true } do |f| %>
  <% if @carousel.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@carousel.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% @carousel.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :headline %><br>
    <%= f.text_field :headline, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :description %><br>
    <%= f.text_area :description, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :image %>
    <%= f.file_field :image, class: "form-control" %>
  </div>

   <div class="form-group">
    <%= f.label :textcolor %>
    <%= f.select :textcolor, [['White', 0], ['Black', 1]] %>
  </div>

  <div class="form-group">
    <%= f.label :placerank %>
    <%= f.select :placerank, [['No Rank', 0], 1, 2, 3, 4, 5, 6, 7, 8, 9, 10] %>
  </div>

  <div class="form-group">
    <%= f.select :item_id, options_from_collection_for_select(@items, "id", "name") %>
  </div>

  <div class="form-group">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/carousels/edit.html.erb
<h1>Editing item</h1>

<%= render 'form' %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

<%= form_tag('/carousels/'+@carousel.id.to_s+'/edit', :method => :get) do %>
	<%= select_tag :artist_id, options_from_collection_for_select(Artist.all, "id", "name") %>
	<%= submit_tag('Find') %>
<% end %>

app/views/carousels/index.html.erb
<h1>Listing Carousels</h1>

<p style='font-size:150%;'>Active: <strong><%= @carousels.select{|x| x.placerank > 0}.length %></strong></p>

<table class='table table-stripped'>
  <thead>
    <tr>
      <th>Color</th>
      <th>Place</th>
      <th>Headline</th>
      <th>Edit</th>
    </tr>
  </thead>

  <tbody>
    <% @carousels.each do |carousel| %>
      <tr <% if carousel.placerank > 0 %>style='color:#c0392b; font-weight:bold;'<% end %>>
        <td><% if carousel.textcolor == 0 %>White<% else %>Black<%end%></td>
        <td><% if carousel.placerank >0 %><%= carousel.placerank %><% else %>Inactive<% end %></td>
        <td><%= carousel.headline %></td>
        <td><%= link_to 'Show', carousel %> <%= link_to 'Edit', edit_carousel_path(carousel) %> <%= link_to 'Destroy', carousel, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New carousel', new_carousel_path %>

app/views/carousels/new.html.erb
<h1>New Carousel</h1>

<%= render 'form' %>

<%= link_to 'Back', carousels_path %>

<%= form_tag('/carousels/new', :method => :get) do %>
	<%= select_tag :artist_id, options_from_collection_for_select(Artist.all, "id", "name") %>
	<%= submit_tag('Find') %>
<% end %>

app/views/carousels/show.html.erb
<div style='text-align:center; margin-top:10px; font-weight:bold;'>
	<%= image_tag(@carousel.image(:medium), style: 'width:800px;') %>
</div>

<div style='text-align:center; margin-top:10px; font-weight:bold;'>
	<%= @carousel.headline %>
</div>

<div style='text-align:center; margin-top:10px; font-weight:bold;'>
	<%= @carousel.description %>
</div>

<div style='text-align:center; margin-top:10px; font-weight:bold;'>
	<%= @carousel.item_id %>-<%= @carousel.item.name %>
</div>

<div style='text-align:center; margin-top:10px;'>
	<%= link_to 'back', carousels_path %>
</div>