config/routes.rb
Rails.application.routes.draw do

  resources :artists, :path => "Authors"

  resources :items

  resources :itemimages

  resources :carts

#  resources :userinfos

  resources :comments

  resources :likes

  resources :orders

  resources :carousels

  resources :pricerequests

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

	root "pages#home"
	get "paintings" => "pages#paintings"
	get "jewellery" => "pages#enamels", as: "enamels"
  get "textiles" => "pages#textiles"
  get "sculptures" => "pages#sculptures"
  get "channel" => "pages#channel"
  get "favorites" => "likes#index"
  get "AboutUs" => "pages#aboutus", as: "aboutus"
  get "Contact" => "pages#contact", as: "contact"
  get "MyFavorites" => "pages#favorites", as: "myfavorites"
  get "ordermanagement" => "pages#ordermanagement"
  get "requestmanagement" => "pages#requestmanagement"
  get 'sitemap.xml' => 'pages#sitemap', :defaults => { :format => 'xml' }

end

app/models/item.rb
class Item < ActiveRecord::Base
	after_create :update_artist_name

	has_many :itemimages
	has_many :orders
	has_many :carts
	has_many :comments
	has_many :likes
	has_many :pricerequests

	belongs_to :artist
	has_one :carousel

	has_attached_file :image, :styles => { :small => '100' ,:medium => "300x300>", :large => "750x750>" }

	validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
	validates :description, presence: true


	def to_param
		"#{id}-artist:#{self.artist.name}-art:#{name.gsub(/ /,"-")}"
	end

	def update_artist_name
		self.update_attribute :artist_name, Artist.find(self.artist_id).name
	end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:show]
  before_action :admin_user, except: [:show]

  respond_to :html

  def index
      @items = Item.all
      respond_with(@items)
  end

  def show
    @commentbuild = Comment.new
    @pricerequestbuild = Pricerequest.new
    respond_with(@item, @itemimagebuild = Itemimage.new, @itemimages = @item.itemimages)
  end

  def new
    @artists = Artist.all
    @item = Item.new
    respond_with(@item)
  end

  def edit
    @artists = Artist.all
  end

  def create
    @item = Item.new(item_params)
    @item.save
    respond_with(@item)
  end

  def update
    @item.update(item_params)
    respond_with(@item)
  end

  def destroy
    @item.destroy
    redirect_to items_path
  end

  private
    def set_item
      @item = Item.find(params[:id])
      @og_title = @item.name.split.map(&:capitalize)*' '+' '+'By '+@item.artist.name.split.map(&:capitalize)*' '
      @og_description = @item.description
      @og_image = @item.image.url(:large)
      @og_price = @item.price.to_s
    end

    def admin_user
      unless current_user.try(:admin?)
        redirect_to :root, notice: "Only admins are authorized for this"
      end
    end

    def item_params
      params.require(:item).permit(:name, :description, :image, :artist_id, :item_type, :item_tag,:date_of_creation, :dimensions, :weight, :shipping, :sold_out , :additional_info, :price, :discount, :quantity)
    end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_comments.html.erb
<div id='comments' style='margin-top:100px;'>
	<h4 style='font-weight:bold; color:#484848;'>COMMENTS:</h4>
	<div class='row'>
		<div class='col-md-10' style='padding-right:0; padding-left:0;'>
			<% @item.comments.each do |comment| %>
				<div class='comment'>
					<p style='color:black; font-weight:bold; font-size:110%; margin-left:20px;'><%= comment.user.name.split.map(&:capitalize)*' ' %></p>
					<p style='margin-left:40px;'><%= comment.ccontent %></p>
				</div>
			<% end %>
		</div>
	</div>
	<% if user_signed_in? %>
		<%= form_for @commentbuild, :html => {class: 'form-group', style: 'margin-top:30px;'}, remote: true do |f| %>
			<%= f.text_area :ccontent, :placeholder => 'Leave a comment here', class: 'form-control', style: 'resize:none; width:73.3%; height:100px; display:inline-block;-webkit-border-top-right-radius: 0;-webkit-border-bottom-right-radius: 0;-moz-border-radius-topright: 0;-moz-border-radius-bottomright: 0;border-top-right-radius: 0;border-bottom-right-radius: 0;' %><%= f.submit 'Leave Comment', class: 'btn btn-default leaveComment'%>
			<%= f.hidden_field :item_id, :value => @item.id %>
		<% end %>
	<% else %>
		<p>You need to be signed into your account to leave a comment.</p>
	<% end %>
</div>

app/views/items/_form.html.erb
<%= form_for @item, html: { multipart: true } do |f| %>
  <% if @item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% @item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %><br>
    <%= f.text_field :name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :description %><br>
    <%= f.text_area :description, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :item_type %><br>
    <%= f.select :item_type, [ 'Painting', 'Enamel', 'Textile', 'Sculpture'], class: "form-control" %>
  </div>

  <div class='form-group'>
    <%= f.label :item_tag %><br>
    <%= f.select :item_tag, [ 'Abstract', 'Modern','Landscape', 'Animals', 'Urban', 'Nature', 'Portrait', 'Ring', 'Necklace', 'Bracelet', 'Earring', 'Pin', 'Icon', 'Felt', 'Batik', 'Composition', 'Still Life', 'Other' ], class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :sold_out%><br>
    <%= f.select :sold_out, [['No',0],['Yes',1]], class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :date_of_creation %><br>
    <%= f.text_field :date_of_creation, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :dimensions %><br>
    <%= f.text_field :dimensions, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :weight %><br>
    <%= f.text_field :weight, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :shipping %><br>
    <%= f.text_field :shipping, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :additional_info %><br>
    <%= f.text_field :additional_info, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :price %><br>
    <%= f.text_field :price, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :discount %><br>
    <%= f.text_field :discount, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :quantity %><br>
    <%= f.text_field :quantity, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :image %>
    <%= f.file_field :image, class: "form-control" %>
  </div>

  <div class="form-group">
    <% unless @item.present? %>
      <%= f.select :artist_id, options_from_collection_for_select(@artists, "id", "name") %>
    <% else %>
      <%= f.collection_select :artist_id, Artist.all ,:id, :name %>
    <% end %>
  </div>

  <div class="form-group">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/items/_likes.html.erb
<div id='likes' style='width:100%; text-align:right;'>
	<% unless current_user.likes.find_by(:item_id => @item.id).present? %>
  		<%= link_to likes_path(like: {:item_id => @item.id}), style: 'text-decoration:none; color:#484848;', method: :post, remote: true do %>
  			<button class='btn btn-default' style='width:100%; text-align:center; margin-top:10px'>
		  		<i class="fa fa-heart fa-lg" style='color:#c0392b;'></i> Add To Favorites
		  	</button>
		<% end %>
	<% else %>
  		<%= link_to like_path(current_user.likes.find_by(:item_id => @item.id)), style: 'text-decoration:none; color:#484848;', method: :delete, remote: true do %>
  			<button class='btn btn-default' style='width:100%; text-align:center; margin-top:10px'>
		  		<i class="fa fa-heart fa-lg" style='color:#484848;'></i> Remove From Favorites
		  	</button>
		<% end %>
	<% end %>
</div>

app/views/items/edit.html.erb
<h1>Editing item</h1>

<%= render 'form' %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

app/views/items/index.html.erb
<%= link_to 'New Item', new_item_path, style: 'font-weight:bold;' %>

<br>

<h1>Listing items</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @items.each do |item| %>
      <tr>
        <td><%= item.name %></td>
        <td><%= link_to 'Show', item %></td>
        <td><%= link_to 'Edit', edit_item_path(item) %></td>
        <td><%= link_to 'Destroy', item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/items/new.html.erb
<h1>New item</h1>

<%= render 'form' %>

<%= link_to 'Back', items_path %>

app/views/items/show.js.erb
<% unless @like.present? %>
	$('#comments').replaceWith('<%= j render("items/comments") %>');
<% else %>
	$('#likes').replaceWith('<%= j render("items/likes") %>')
<% end %>