config/routes.rb
Rails.application.routes.draw do

  resources :artists, :path => "Authors"

  resources :items

  resources :itemimages

  resources :carts

#  resources :userinfos

  resources :comments

  resources :likes

  resources :orders

  resources :carousels

  resources :pricerequests

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

	root "pages#home"
	get "paintings" => "pages#paintings"
	get "jewellery" => "pages#enamels", as: "enamels"
  get "textiles" => "pages#textiles"
  get "sculptures" => "pages#sculptures"
  get "channel" => "pages#channel"
  get "favorites" => "likes#index"
  get "AboutUs" => "pages#aboutus", as: "aboutus"
  get "Contact" => "pages#contact", as: "contact"
  get "MyFavorites" => "pages#favorites", as: "myfavorites"
  get "ordermanagement" => "pages#ordermanagement"
  get "requestmanagement" => "pages#requestmanagement"
  get 'sitemap.xml' => 'pages#sitemap', :defaults => { :format => 'xml' }

end

app/views/layouts/_carousel.html.erb
 <!-- Carousel
    ================================================== -->
    <div id="myCarousel" class="carousel slide" data-ride="carousel">
      <!-- Indicators -->
      <ol class="carousel-indicators">
        <% @carousels.each_with_index do |carousel, index| %>
          <% if index == 0 %>
            <li data-target="#myCarousel" data-slide-to="<%= index %>" class="active"></li>
          <% else %>
            <li data-target="#myCarousel" data-slide-to="<%= index %>"></li>
          <% end %>
        <% end %>
      </ol>
      <div class="carousel-inner" role="listbox">
        <% @carousels.each_with_index do |carousel, index| %>
          <% if index == 0 %>
            <div class="item active">
              <table id="wrapper">
                  <tr>
                     <td><img src="<%= carousel.image(:medium) %>" alt="slide"></td>
                  </tr>
               </table>
              <div class="container">
                <div class="carousel-caption">
                  <%= link_to item_path(carousel.item_id), style:'color:white; text-decoration:none;' do %>
                    <h1 <% unless carousel.textcolor == 0 %>style='color:black;'<% end %>><%= carousel.headline %></h1>
                    <p <% unless carousel.textcolor == 0 %>style='color:black;'<% end %>><%= carousel.description.html_safe %></p>
                  <% end %>
                </div>
              </div>
            </div>
          <% else %>
            <div class="item">
              <table id="wrapper">
                  <tr>
                     <td><img src="<%= carousel.image(:medium) %>" alt="slide"></td>
                  </tr>
               </table>
              <div class="container">
                <div class="carousel-caption">
                  <%= link_to item_path(carousel.item_id), style:'color:white; text-decoration:none;' do %>
                    <h1 <% unless carousel.textcolor == 0 %>style='color:black;'<% end %>><%= carousel.headline %></h1>
                    <p <% unless carousel.textcolor == 0 %>style='color:black;'<% end %>><%= carousel.description.html_safe %></p>
                  <% end %>
                </div>
              </div>
            </div>
          <% end %>
        <% end %>
      </div>
      <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
      </a>
      <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
      </a>
    </div><!-- /.carousel -->

<% unless mobile_device? %>
    <div id='search-fix' class='container-fluid' style='background-color:white;'>
        <div id='filters' class='row'>
          <div class='col-md-2 col-md-offset-1 tex-center'>
          <%= search_form_for @q, url: root_path, html: { class: 'input-group', style: 'margin-top:10px;'} do |f| %>
              <span class="input-group-btn">
                <button type='submit;' class="btn btn-default" type="button" style='-webkit-border-top-right-radius: 0px;-webkit-border-bottom-right-radius: 0px;-moz-border-radius-topright: 0px;-moz-border-radius-bottomright: 0px;border-top-right-radius: 0px;border-bottom-right-radius: 0px; border-right:none;'><i class="fa fa-search fa-lg"></i></button>
              </span><%= f.search_field :name_or_artist_name_cont, placeholder: 'Search...', class: 'form-control', style: 'margin-left:-1px;' %>
            <% end %>
          </div>
          <div id='naxati' class='col-md-2' style="text-align:center; padding-top:15px; padding-bottom:15px;">
            <%= link_to "Paintings".upcase, paintings_path, style: 'text-decoration:none; font-weight:bold; font-size:110%; color:#444;' %>
          </div>
          <div id='minankari' class='col-md-2' style="text-align:center; padding-top:15px; padding-bottom:15px;">
            <%= link_to "Jewellery".upcase, enamels_path, style: 'text-decoration:none; font-weight:bold; font-size:110%; color:#444;' %>
          </div>
          <div id='nacheri' class='col-md-2' style="text-align:center; padding-top:15px; padding-bottom:15px;">
            <%= link_to "Textiles".upcase, textiles_path, style: 'text-decoration:none; font-weight:bold; font-size:110%; color:#444;' %>
          </div>
          <div id='kandakeba' class='col-md-2' style="text-align:center; padding-top:15px; padding-bottom:15px;">
            <%= link_to "Sculptures".upcase, sculptures_path, style: 'text-decoration:none; font-weight:bold; font-size:110%; color:#444;' %>
          </div>
        </div>
    </div>
<% else %>
    <div id='search-fix' class='container-fluid' style='background-color:white;'>
        <div id='filters' class='row'>
          <div class='col-md-2 col-md-offset-1 text-center' style='padding-bottom:10px;'>
          <%= search_form_for @q, url: root_path, html: { class: 'input-group', style: 'margin-top:10px;'} do |f| %>
              <span class="input-group-btn">
                <button type='submit;' class="btn btn-default" type="button" style='-webkit-border-top-right-radius: 0px;-webkit-border-bottom-right-radius: 0px;-moz-border-radius-topright: 0px;-moz-border-radius-bottomright: 0px;border-top-right-radius: 0px;border-bottom-right-radius: 0px; border-right:none;'><i class="fa fa-search fa-lg"></i></button>
              </span><%= f.search_field :name_or_artist_name_cont, placeholder: 'Search...', class: 'form-control', style: 'margin-left:-1px;' %>
            <% end %>
          </div>
        </div>
    </div>
<% end %>

<script>
 fixed_home = $('#search-fix');
 offset_home = $('#search-fix').offset();
  $(window).scroll(function(e){
    if ($(this).scrollTop() > offset_home.top && fixed_home.css('position') != 'fixed'){
      fixed_home.css({'position': 'fixed', 'top': '0px', 'z-index': '1'});
    }else if ($(this).scrollTop() < offset_home.top && fixed_home.css('position') == 'fixed' ){
      fixed_home.css({'position': 'relative', 'z-index': '0'});
    }
  });
</script>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-static-top navbar-default" role="navigation" style='margin-bottom:0;'>
  <div class='container'>
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to root_path, class: "navbar-brand" do %>ARTIVERIA<% end %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse navbar-ex1-collapse">
      <ul class="nav navbar-nav">
        <li><%= link_to "PAINTINGS", paintings_path %></li>
        <li><%= link_to "JEWELLERY", enamels_path %></li>
        <li><%= link_to "TEXTILES", textiles_path %></li>
        <li><%= link_to "SCULPTURES", sculptures_path %></li>
        <li><%= link_to "AUTHORS", artists_path %></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
      <li><%= link_to carts_path do %><span class='glyphicon glyphicon-shopping-cart'></span> CART<% end %></li>
          <% if user_signed_in? %>
            <% if current_user.try(:admin?)%>
              <li><%= link_to "ITEMS", items_path %></li>
               <li><%= link_to "CAROUSELS", carousels_path %></li>
            <% end %>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">MY ACCOUNT<span class="caret"></span></a>
              <ul class="dropdown-menu" role="menu">
                <li><%= link_to "My Favorites", myfavorites_path %></li>
                <li><%= link_to "My Orders", orders_path %></li>
                <% if current_user.try(:admin?) %>
                  <li><%= link_to "Order Management", ordermanagement_path %></li>
                  <li><%= link_to "Request Management", requestmanagement_path %></li>
                <% end %>
                <li class="divider"></li>
                <li><%= link_to "Account Settings", edit_user_registration_path %></li>
              </ul>
            </li>
            <li><%= link_to "LOG OUT", destroy_user_session_path, method: :delete %></li>
          <% else %>
            <li><%= link_to "SIGN IN", new_user_session_path, style: "font-weight:bold;" %></li>
            <li><%= link_to "SIGN UP", new_user_registration_path, style: "font-weight:bold;" %></li>
            <li data-toggle="tooltip" data-placement="bottom" title="Sign In With Facebook"><%= link_to user_omniauth_authorize_path(:facebook) do %><i class="fa fa-facebook-square fa-lg" style='color:white;'></i><% end %></li>
          <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container -->
</nav>

<script>
$(document).ready(function(){
  $('.dropdown-toggle').dropdown();
});
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Georgian Art at Artiveria.com</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name='description' content='Artiveria.com is an online gallery where you can buy Gerogian art online. We are a joint venture of an American company Artiveria LLC and of its sister company Artiveria Ltd. based in Tbilisi, Georgia. We ship worldwide.'>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <% if @og_title.present? %><meta property="og:title" content='<%= @og_title %>' /><% end %>
  <meta property="og:site_name" content='Artiveria' />
  <meta property='og:url' content='<%= request.original_url %>' />
  <% if @og_description.present? %><meta property='og:description' content='<%= @og_description %>' /><% end %>
  <meta property='fb:app_id' content='1396126384014923' />
  <% if @og_image.present? %><meta property='og:image' content='<%= image_url @og_image %>' /><% end %>
  <meta name="p:domain_verify" content="bd191a747b42f41b5eb0961d9fa7c916"/>
  <% if @og_price.present? %>
    <meta property='og:type' content='product' />
    <meta property='og:price:amount' content='<%= @og_price %>' />
    <meta property='og:price:currency' content='USD' />
  <% end %>
  <%= favicon_link_tag 'Favicon.ico' %>
</head>
<body>

  <%= render 'layouts/header' %>

  <% flash.each do |name, msg| %>
      <script>
      var n = noty({
        text: '<p style="width:100%; margin-top:15px; margin-bottom:15px; text-align:center; font-weight:bold; font-size:120%;"><%= msg %></p>',
        layout: 'topRight',
        type: 'information',
        animation: {
          open: 'animated fadeInRight', // Animate.css class names
          close: 'animated flipOutY', // Animate.css class names
          speed: 500 // unavailable - no need
        }
      });
      </script>
  <% end %>

  <% if current_page?(root_path) %>
    <%= render "layouts/carousel" %>
  <% end %>

  <div id="page-after-navbar">
    <div class="container" style='min-height:700px;'>
      <div class='row'>
    	 <%= yield %>
    	</div>
    </div>
  </div>

  <%= render "layouts/footer" %>


</body>
</html>